"""add_ussd_pin_hash_to_users

Revision ID: 9ef9f71f4d78
Revises: 3cf2e740e65b
Create Date: 2026-05-23 16:56:31.202214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ef9f71f4d78'
down_revision: Union[str, None] = '3cf2e740e65b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ussd_pin_hash', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ussd_pin_hash')
    # ### end Alembic commands ###
